### ISSUE TITLE
`halo2-snark-aggregator` process killed when running `verify_run` command

### ISSUE THREAD

**Issue by jacktnho** [scroll-tech/halo2-snark-aggregator#10]
Process was killed while running `verify_run`, there wasn't any back trace given even `RUST_BACKTRACE=1` is set. 
```
blackhole@ROG-G14:~/projects/scroll-tech/halo2-snark-aggregator/halo2-snark-aggregator$ RUST_BACKTRACE=1 cargo run --release -- --command verify_run --nproofs 2 --folder-path ./output --template-path ../halo2-snark-aggregator-solidity/templates
    Finished release [optimized] target(s) in 0.05s
     Running `/home/blackhole/projects/scroll-tech/halo2-snark-aggregator/target/release/halo2-snark-aggregator --command verify_run --nproofs 2 --folder-path ./output --template-path ../halo2-snark-aggregator-solidity/templates`
Killed
```

Here is my env: 
ASUS ROG G14 with AMD Ryzen 9 4900HS & 24GB Memory 
Ubuntu 20.04 (kernel:　5.10.102.1-microsoft-standard-WSL2).

**Comment by lispc** [comment]
24G is too small... I myself use a server with 700GB

**Comment by jacktnho** [comment]
> 

Do you have any recommended specs or env for running that? 
Is there any estimation on the required resources?

**Comment by jay-woods** [comment]
change to some small degree?

**Comment by xgaozoyoe** [comment]
Sample tests can be run under 64G memory with no problem. But needs nearly 128G for single evm-circuit aggregation at the moment.
