### ISSUE TITLE
build error in latest commit (58cb081d)

### ISSUE THREAD

**Issue by jacktnho** [scroll-tech/halo2-snark-aggregator#16]
Hi there, it seems that the latest commit 58cb081d cannot be built successfully.
Looks like broken dependencies?
![index](https://user-images.githubusercontent.com/24970449/184539625-e0b3028e-86b8-4c0d-9b64-da0cc77f863e.jpg)

**Comment by jacktnho** [comment]
Any one can help on this?

**Comment by xgaozoyoe** [comment]
@jacktnho  Do you still have building problem on main branch?
